---
# - name: Install apt using task 
#   hosts: 172.31.8.211
#   become: yes
#   gather_facts: yes
#   vars:
#     ansible_ssh_user: ec2-user 
#     ansible_ssh_private_key_file: "/home/ec2-user/files/sample.pem"
#   tasks:    

#     - name: python script
#       command: python3 /home/ec2-user/hameed-test.py
#       register: result

#     - name: print result
#       debug:
#         var: result 

- name: Install apt using task 
  hosts: localhost
  remote_user: root
  become: yes
  gather_facts: yes
  # vars:
  #   ansible_ssh_user: ec2-user 
  #   ansible_ssh_private_key_file: "/home/ec2-user/files/sample.pem"
  tasks:
    
    # - name: Execute Python script through shell module
    #   shell: python3 /home/ec2-user/test.py
    #   delegate_to: 35.154.24.128
      

    - name: python script
      command: python3 /home/ec2-user/hameed-test.py
      register: result


