---
- name: Install apt using task 
  hosts: 35.154.24.128
  become: yes
  gather_facts: yes
  vars:
    ansible_ssh_user: ec2-user 
    ansible_ssh_private_key_file: "/home/ec2-user/files/sample.pem"
  tasks:    

    - name: python script
      command: python3 /home/ec2-user/hameed-test.py
      register: result

    - name: print result
      debug:
        var: result 


