---
- name: Install a package
  hosts: all
  become: true
  vars:
    - Name: Rayank

  tasks:

    - name: Print A Name
      debug:
         msg: "Name is {{ Name }}"

    - name: Install apache Service
      apt:
        name: cmatrix
        state: present
