- name: Create ServiceNow Change Request
  hosts: localhost

  vars:
    servicenow_api_url: "{{ ansible_user }}"
    parts: "{{ ansible_password }}"

  tasks:
    - name: Set variables
      set_fact:
        parts: "{{ parts.split('~') }}"

    - name: Assign parts to variables
      set_fact:
        servicenow_username: "{{ parts[0] }}"
        servicenow_password: "{{ parts[1] }}"

    - name: Create Change Request in ServiceNow
      uri:
        url: "{{ servicenow_api_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: |
          {
            "short_description": "Incident Title test from playbook",
            "urgency": "3",
            "impact": "3"
          }
        status_code: 201
        validate_certs: no
        force_basic_auth: yes
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
      register: response

    - name: Check API response
      debug:
        var: response

