- name: Update ServiceNow CTASK
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Include the generated token
    include_tasks: "Testtoken.yaml"
  - name: Construct URL with parameters
    set_fact:
      api_url: "{{ ipaas_uri }}&companyName={{ companyName | urlencode }}&withWorknotes=true"
  - name: Update CTASK in ServiceNow
    uri:
     url: "{{ api_url }}"
     method: PATCH
     timeout: 60
     headers:
      Authorization: "Bearer {{ servicenow_token }}"
      Content-Type: "application/json"
     body_format: json
     body: '{
    "state":  "{{ state }}",
    "activity":  [
                     {
                         "workLogType":  "{{ logType}}",
                         "workLogDescription":  "{{ workNotes }}"
                     }
                 ],
    "taskCoordinator":  "{{ assignee }}"
   }'
    
     status_code: 200
    register: response
  - name: Check API response
    debug:
      var: response